host:
  ip: 127.0.0.1
  port: 7701
  path: /plugin/2
  mode: TCP
  volumeMethod: /plugin/1/parameter/0
  performanceMethod: /performance/num
fxb:
  path: 'D:\\vsthostx64_beta\\Data\\Bank-1\\P-1FX2.fxb'
  temppath: 'D:\\vsthostx64_beta\\Data\\Bank-1\\P0FX2.fxb'
config:
  volume: 100
